name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['16.x']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: Compile TypeScript
        run: npm run compile
      - name: Run headless tests - specific version
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test:specificVersion
      - name: Run headless tests - latest version
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test:latest
      - name: Run headless tests - legacy version
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test:legacy
