name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['20.x']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Compile TypeScript
        run: npm run compile
      - name: Run headless tests - specific version
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test:minSupportVersion
      - name: Run headless tests - latest version
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test:latest
      # - name: Run headless tests - legacy version
      #  uses: coactions/setup-xvfb@v1
      #  with:
      #    run: npm run test:legacy
